### ISSUE TITLE
UnsatisfiedLinkError: No implementation found for void com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.native_init()

### ISSUE THREAD

**Issue by wilburx9** [acrcloud/acrcloud_sdk_android_extr#1]
I cloned this project and and copied the `.so` files to my project's `jniLibs` folder.

After that, it looked like this:

[![screenshot][2]][2]

However, when I tried using the library it throws:

    09-18 10:22:53.861 18439-19193/com.mopo.audiofingerprinter W/linker: libACRCloudExtrTool.so: unused DT entry: type 0x6ffffffe arg 0x4718
    09-18 10:22:53.861 18439-19193/com.mopo.audiofingerprinter W/linker: libACRCloudExtrTool.so: unused DT entry: type 0x6fffffff arg 0x2
    09-18 10:22:53.871 18439-19193/com.mopo.audiofingerprinter E/art: No implementation found for void com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.native_init() (tried Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init and Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init__)
    09-18 10:22:53.881 18439-19193/com.mopo.audiofingerprinter E/UncaughtException: java.lang.UnsatisfiedLinkError: No implementation found for void com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.native_init() (tried Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init and Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init__)
                                                                                    at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.native_init(Native Method)
                                                                                    at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.<clinit>(ACRCloudExtrTool.java:57)
                                                                                    at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.createFingerprintByFile(ACRCloudExtrTool.java:0)
                                                                                    at com.mopo.audiofingerprinter.tageditor.ACRCloudRecognizer.recognizeByFile(ACRCloudRecognizer.java:129)
                                                                                    at com.mopo.audiofingerprinter.tageditor.TestActivity$RecThread.run(TestActivity.java:84)
    09-18 10:22:54.132 18439-19193/com.mopo.audiofingerprinter E/AndroidRuntime: FATAL EXCEPTION: Thread-51298
                                                                             Process: com.mopo.audiofingerprinter, PID: 18439
                                                                             java.lang.UnsatisfiedLinkError: No implementation found for void com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.native_init() (tried Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init and Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init__)
                                                                                 at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.native_init(Native Method)
                                                                                 at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.<clinit>(ACRCloudExtrTool.java:57)
                                                                                 at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.createFingerprintByFile(ACRCloudExtrTool.java:0)
                                                                                 at com.mopo.audiofingerprinter.tageditor.ACRCloudRecognizer.recognizeByFile(ACRCloudRecognizer.java:129)
                                                                                 at com.mopo.audiofingerprinter.tageditor.TestActivity$RecThread.run(TestActivity.java:84)

The weird thing, is that the compiled project I cloned is working without errors. I have even attempted copying the classes from the demo and still it didn't work.

Please note that the feaures I am using `libACRCloudEngine.so` is working perfectly. So it's `libACRCloudExtrTool.so` that is the problem here.

  [2]: https://i.stack.imgur.com/Bfnd1.png

**Comment by qiuxuewen** [comment]
"acrcloud_sdk_android_extr SDK" and "ACRCloud-android-sdk" that download from [console.acrcloud.com/tools] are different.
If you want to use "libbACRCloudExtrTool.so", please refer to [this demo project](https://github.com/acrcloud/acrcloud_sdk_android_extr/tree/master/ACRCloudExtrToolDemo).
If you want to use "libACRCloudEngine.so", please refer to [this demo project](https://ap-console.acrcloud.com/downloads/sdk/android).

**Comment by Osas-Solo** [comment]
Hello, were you able to find a fix to this issue?

**Comment by Osas-Solo** [comment]
> Hello, were you able to find a fix to this issue?

**Comment by Osas-Solo** [comment]
Hello, were you able to find a fix to this issue?

> I cloned this project and and copied the `.so` files to my project's `jniLibs` folder.
> 
> After that, it looked like this:
> 
> [![screenshot](https://camo.githubusercontent.com/9e191da5da1d22b30e99e6afa091f942caa406b90f44fee05e644ef7e8f9d68e/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f42666e64312e706e67)](https://i.stack.imgur.com/Bfnd1.png)
> 
> However, when I tried using the library it throws:
> 
> ```
> 09-18 10:22:53.861 18439-19193/com.mopo.audiofingerprinter W/linker: libACRCloudExtrTool.so: unused DT entry: type 0x6ffffffe arg 0x4718
> 09-18 10:22:53.861 18439-19193/com.mopo.audiofingerprinter W/linker: libACRCloudExtrTool.so: unused DT entry: type 0x6fffffff arg 0x2
> 09-18 10:22:53.871 18439-19193/com.mopo.audiofingerprinter E/art: No implementation found for void com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.native_init() (tried Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init and Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init__)
> 09-18 10:22:53.881 18439-19193/com.mopo.audiofingerprinter E/UncaughtException: java.lang.UnsatisfiedLinkError: No implementation found for void com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.native_init() (tried Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init and Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init__)
>                                                                                 at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.native_init(Native Method)
>                                                                                 at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.<clinit>(ACRCloudExtrTool.java:57)
>                                                                                 at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.createFingerprintByFile(ACRCloudExtrTool.java:0)
>                                                                                 at com.mopo.audiofingerprinter.tageditor.ACRCloudRecognizer.recognizeByFile(ACRCloudRecognizer.java:129)
>                                                                                 at com.mopo.audiofingerprinter.tageditor.TestActivity$RecThread.run(TestActivity.java:84)
> 09-18 10:22:54.132 18439-19193/com.mopo.audiofingerprinter E/AndroidRuntime: FATAL EXCEPTION: Thread-51298
>                                                                          Process: com.mopo.audiofingerprinter, PID: 18439
>                                                                          java.lang.UnsatisfiedLinkError: No implementation found for void com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.native_init() (tried Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init and Java_com_mopo_audiofingerprinter_tageditor_ACRCloudExtrTool_native_1init__)
>                                                                              at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.native_init(Native Method)
>                                                                              at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.<clinit>(ACRCloudExtrTool.java:57)
>                                                                              at com.mopo.audiofingerprinter.tageditor.ACRCloudExtrTool.createFingerprintByFile(ACRCloudExtrTool.java:0)
>                                                                              at com.mopo.audiofingerprinter.tageditor.ACRCloudRecognizer.recognizeByFile(ACRCloudRecognizer.java:129)
>                                                                              at com.mopo.audiofingerprinter.tageditor.TestActivity$RecThread.run(TestActivity.java:84)
> ```
> 
> The weird thing, is that the compiled project I cloned is working without errors. I have even attempted copying the classes from the demo and still it didn't work.
> 
> Please note that the feaures I am using `libACRCloudEngine.so` is working perfectly. So it's `libACRCloudExtrTool.so` that is the problem here.
